#!/usr/bin/env python
# This is my first script.
# pip install docker-py

import re
from docker import Client

try:
  import json
except ImportError:
  import simplejson as json

env = {
  '_meta': {}
}


cli = Client(base_url='unix://var/run/docker.sock')

for cnt in cli.containers():
  name = cnt['Names'][0].replace('/','')
  info =  cli.inspect_container(cnt['Id'])
  ipaddr = info['NetworkSettings']['IPAddress']
  lbls = info['Config']['Labels']
  env[name] = {'hosts': [ipaddr]}
  if 'group' in lbls:
    group = lbls['group']
    if group in env:
      env[group]['hosts'].append(ipaddr)
    else:
      env[group] = {'hosts': [ipaddr]}

# HOSTS_PATH = 'hosts'

# HOSTS_PATH = '/etc/hosts'

# hosts = [['127.0.0.1', 'localhost']]
# base_dns = "docker"


# print(hosts)

# #f = open('./provision/hosts', 'w')
# #f.write("[app]\n")
# #for x in hosts[1:]:
#     #f.write("{0}\n".format(x[1]))
# #f.close()\

print json.dumps(env)
